from datetime import datetime
import numpy as np

class ClinicalReportGenerator:
    """
    Generates a text-based Clinical Neurophysiology Report.
    """
    def __init__(self):
        pass

    def generate(self, metrics, analysis, events_log):
        """
        metrics: dict (r, k, bsr, metabolic_reserve)
        analysis: dict (spectral, background, etc)
        events_log: list of event dicts
        """
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Calculate Dominant Frequency
        dom_band = "N/A"
        max_pwr = 0
        if analysis and "spectral" in analysis:
            for band, vals in analysis["spectral"].items():
                mean_p = np.mean(vals)
                if mean_p > max_pwr:
                    max_pwr = mean_p
                    dom_band = band
        
        # Event Summary
        spike_count = len([e for e in events_log if e['type'] == 'SPIKE'])
        artifact_count = len([e for e in events_log if e['type'] == 'ARTIFACT'])
        
        report = f"""
================================================================
           NEUROSYNC CORTEX SIMULATION - CLINICAL REPORT
================================================================
Date/Time: {timestamp}
Patient ID: ANALOG-SIM-001
Protocol:   Standard 10-20 EEG Monitoring

----------------------------------------------------------------
1. QUANTITATIVE METRICS
----------------------------------------------------------------
Phase Coherence (Global Synchronization): {metrics.get('order_parameter', 0):.2f}
Coupling Strength (Synaptic Gain):        {metrics.get('coupling_strength', 0):.1f}
Burst Suppression Ratio (BSR):            {metrics.get('bsr', 0)*100:.1f}%
Metabolic Reserve:                        {metrics.get('metabolic_reserve', 0)*100:.1f}%

----------------------------------------------------------------
2. SPECTRAL ANALYSIS
----------------------------------------------------------------
Background Rhythm Classification: {analysis.get('background', 'N/A')}
Dominant Frequency Band:          {dom_band.upper()} ({max_pwr:.1f} uV^2/Hz)

----------------------------------------------------------------
3. EVENT LOG SUMMARY
----------------------------------------------------------------
Total Recording Time: --
Epileptiform Spikes Detected: {spike_count}
Artifact Events (Blink/Muscle): {artifact_count}

----------------------------------------------------------------
4. AUTOMATED CLINICAL IMPRESSION
----------------------------------------------------------------
{self._generate_impression(metrics, dom_band, spike_count)}

----------------------------------------------------------------
* This report is generated by an AI-assisted simulation engine.
* Not for medical diagnostic use.
================================================================
"""
        return report

    def _generate_impression(self, metrics, dom_band, spikes):
        impressions = []
        
        bsr = metrics.get('bsr', 0)
        reserve = metrics.get('metabolic_reserve', 1.0)
        coupling = metrics.get('coupling_strength', 0.5)
        
        if bsr > 0.5:
            impressions.append("CRITICAL: Significant Burst-Suppression pattern indicating deep sedation or metabolic failure.")
        
        if reserve < 0.3:
            impressions.append("WARNING: Metabolic reserve critically low (Excitotoxicity risk).")
            
        if coupling > 4.0:
            impressions.append(f"PATHOLOGY: Hypersynchronous activity consistent with generalized seizure. {spikes} spikes detected.")
        elif coupling < 0.2:
            impressions.append("STATE: Electrocerebral silence/inactivity.")
        else:
            if dom_band == 'Alpha':
                impressions.append("NORMAL: Posterior dominant Alpha rhythm preserved. Healthy resting state.")
            elif dom_band == 'Delta':
                impressions.append("ABNORMAL: Diffuse Delta slowing detected (Encephalopathy or Sleep artifacts).")
            elif dom_band == 'Beta':
                impressions.append("STATE: Beta dominance indicating active cognitive processing or anxiety.")
                
        if len(impressions) == 0:
            impressions.append("Unremarkable EEG study.")
            
        return "\n".join(impressions)
